"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const definition_1 = require("./definition");
exports.INTERVAL_METRICS = [{
        name: 'load',
        key: 'duration',
    }, {
        name: 'domContentLoaded',
        key: 'domContentLoadedEventStart',
    }, {
        name: 'timeToFirstByte',
        key: 'responseStart'
    }];
exports.DURATION_METRICS = [{
        name: 'redirect',
        startKey: 'redirectStart',
        endKey: 'redirectEnd',
        type: definition_1.DurationType.Networking
    }, {
        name: 'unloadEvent',
        startKey: 'unloadEventStart',
        endKey: 'unloadEventEnd',
        type: definition_1.DurationType.Client,
    }, {
        name: 'appcache',
        startKey: 'fetchStart',
        endKey: 'domainLookupStart',
        type: definition_1.DurationType.Networking
    }, {
        name: 'dnsLookup',
        startKey: 'domainLookupStart',
        endKey: 'domainLookupEnd',
        type: definition_1.DurationType.Networking
    }, {
        name: 'stalled',
        startKey: 'domainLookupEnd',
        endKey: 'connectStart',
        type: definition_1.DurationType.Networking
    }, {
        name: 'connect',
        startKey: 'connectStart',
        endKey: 'connectEnd',
        type: definition_1.DurationType.Networking
    }, {
        name: 'ssl',
        startKey: 'secureConnectionStart',
        endKey: 'connectEnd',
        type: definition_1.DurationType.Networking
    }, {
        name: 'request',
        startKey: 'requestStart',
        endKey: 'responseStart',
        type: definition_1.DurationType.Server
    }, {
        name: 'response',
        startKey: 'responseStart',
        endKey: 'responseEnd',
        type: definition_1.DurationType.Server
    }, {
        name: 'parseHTML',
        startKey: 'responseEnd',
        endKey: 'domInteractive',
        type: definition_1.DurationType.Client
    }, {
        name: 'loadCritialResources',
        startKey: 'responseEnd',
        endKey: 'domContentLoadedEventStart',
        type: definition_1.DurationType.Client
    }, {
        name: 'domReadyEvent',
        startKey: 'domContentLoadedEventStart',
        endKey: 'domContentLoadedEventEnd',
        type: definition_1.DurationType.Client
    }, {
        name: 'loadAllResources',
        startKey: 'responseEnd',
        endKey: 'domComplete',
        type: definition_1.DurationType.Client
    }, {
        name: 'loadEvent',
        startKey: 'loadEventStart',
        endKey: 'loadEventEnd',
        type: definition_1.DurationType.Client
    }];
//# sourceMappingURL=metrics.js.map